achminupdata:
    container_name: achminup-data
    image: bqqbarbhg/achminup-data
    env_file:
        - common.env
achminup:
    container_name: achminup
    image: bqqbarbhg/achminup
    env_file:
        - common.env
        - achminup.env
    volumes_from:
        - achminupdata
